
import os
import sbms

# get env object and clone it
Import('*')
env = env.Clone()

# Install all files except 'SConscript'
scripts = env.Glob('*')
for script in scripts:
	myscript = '%s' % script  # convert to simple string
	if 'SConscript' in myscript: continue
	
	if os.path.isdir(myscript):
		SConscript(dirs=[script], exports='env osname', duplicate=0)
	else:
		sbms.script(env, script)


