
import os

Import('env osname')

# Loop over libraries, building each
subdirs = ['include', 'BCAL', 'FCAL', 'DANA', 'TAGGER', 'HDGEOMETRY', 'TRACKING', 'CCAL', 'START_COUNTER', 'TRIGGER', 'CDC', 'FDC', 'PID', 'ANALYSIS', 'CERE', 'HDDM', 'RICH', 'TOF', 'PAIR_SPECTROMETER']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

