
# Default makefile for HDGeant
# this just invokes make in the gelhad directory and
# then make with Makefile.bms in this directory.


all:
	make -C gelhad
	make -f Makefile.bms

clean:
	make -C gelhad clean
	make -f Makefile.bms clean

