OStype = $(shell uname)
ARCHtype = $(shell uname -m)
BINDIR = ../bin.$(OStype)

#--------------------------------------------------------------------
# The symbol SPECIAL is used to active any of the following switches
# to enable custom versions of the simulation program.
#NTUPLE_OPTIONS = -DBACKGROUND_STUDIES
#NTUPLE_OPTIONS = -DBACKGROUND_PROFILING
#NTUPLE_OPTIONS = -DWERNERS_VTX_NTUPLE
NTUPLE_OPTIONS = -DCERENKOV_PID_NTUPLE
# Enable the following line to turn off writing out hddm data 
#IO_OPTIONS = -DDISABLE_OUTPUT
#--------------------------------------------------------------------

SWITCHES = $(IO_OPTIONS) $(NTUPLE_OPTIONS)

ifeq ($(OStype),Linux)
	ifeq ($(ARCHtype),alpha)
		CC	:= gcc
		CPP	:= g++
		F77	:= g77
		NETLIB := -lnsl
		XLIBS  := -L/usr/X11R6/lib -lXpm -lSM -lXm -lXt -lICE -lXext -lX11 -lXp -ldl
		COPTS = -g $(SWITCHES)
		FOPTS = -g -Wno-globals $(SWITCHES)
		GLIBS 	:= -L/usr/lib/gcc-lib/alpha-redhat-linux/egcs-2.91.66/ -lg2c 
	else
		CC	:= gcc
		CPP	:= g++
		F77	:= g77
		NETLIB := -lnsl
		XLIBS  := -L/usr/X11R6/lib -lXpm -lSM -lXm -lXt -lICE -lXext -lX11 -lXp -ldl
		COPTS = -g $(SWITCHES)
		FOPTS = -g -Wno-globals $(SWITCHES)
		GLIBS	:= -lXmu -lSM -lICE -lpthread
		EXPORTDYNAMIC = -Wl,-export-dynamic
		STATIC = -Wl,-Bstatic
	endif
endif
ifeq ($(OStype),OSF1)
	CC	:= cc
	CPP	:= g++
	F77	:= f77
	NETLIB := 
        EXPORTDYNAMIC :=
	STATIC	:=
	XLIBS  := -L/usr/lib -lXm -lSM -lICE -lXt -lX11 -lm -lPW -ldnet_stub
	COPTS = -g -D_Tru64 $(SWITCHES)
	FOPTS = -g -fpe4 $(SWITCHES)
	LOPTS = -g -non_shared -fpe4
	GLIBS 	:= -L/r5d1/applications/gcc3/lib/gcc-lib/alphaev5-dec-osf4.0f/ -lg2c -L/r5d1/applications/gcc3/lib/gcc-lib/alphaev5-dec-osf4.0f/3.3/ -lgcc
endif
ifeq ($(OStype),SunOS)
	CC	:= cc
	CPP	:= CC
	F77	:= f77
	NETLIB	:= 
	EXPORTDYNAMIC :=
	STATIC	:=
	XLIBS	:= -L/usr/lib -lXm -lSM -lICE -lXt -lX11 -lm 
	COPTS	:= -g $(SWITCHES)
	FOPTS	:= -g $(SWITCHES)
	LOPTS	:= -g
	GLIBS	:=
endif
ifeq ($(OStype),Darwin)
	CC	:= gcc
	CPP	:= g++
	F77	:= g77
	NETLIB 	:=
	XLIBS  	:= -L/usr/X11R6/lib -lXpm -lSM -lXm -lXt -lICE -lXext -lX11 -lXp -ldl
	COPTS = -g $(SWITCHES)
	FOPTS = -g -Wno-globals $(SWITCHES)
	GLIBS	:= -L$(CERN_ROOT)/lib -lcompat /usr/lib/libgcc.a
endif

HDDS = ../hdds
HDDM = ../hddm

ifeq ($(OStype),OSF1)
 	MISC_FIXES := vunit.o gsrotm.o fint.o gthion.o
else
	MISC_FIXES :=
endif

AUXF = gufld.o guhadr.o gukine.o guout.o guphad.o gustep.o guxcs.o \
       gelhad/gtgama.o gelhad/caspim.o gelhad/caspip.o gpairg.o \
       hddsGeant3.o goptimize.o cobrems.o
AUXC = hddmInput.o hddmOutput.o hddm_s.o \
       hitStart.o hitCDC.o hitFDC.o hitBCal.o hitCerenkov.o hitFTOF.o \
       hitFCal.o bintree.o hitutil.o memcheck.o timel.o trapfpe.o

GXFIXED = gxcs.o gxphys.o
GELHAD = gelhad/libgelhad.a

CERNLIB = $(CERN_ROOT)/bin/cernlib

hdgeant++: gxint.o uginit.o uglast.o $(GELHAD) $(AUXF) $(AUXC) $(GXFIXED) \
           $(MISC_FIXES)
	$(F77) -o $@ gxint.o uginit.o uglast.o \
	   $(AUXF) $(AUXC) $(GXFIXED) $(MISC_FIXES) \
	   -Lgelhad -lgelhad \
	   `cernlib -v $(CERN_LEVEL) geant321 pawlib graflib/Motif packlib mathlib` \
	   $(EXPORTDYNAMIC) $(GLIBS)

hdgeant: hdgeant.o uginit.o uglast.o $(GELHAD) $(AUXF) $(AUXC) $(MISC_FIXES)
	$(F77) $(LOPTS) -o $@ -I$(CERN_ROOT)/include $(STATIC) \
	  hdgeant.o uginit.o uglast.o $(AUXF) $(AUXC) -Lgelhad -lgelhad \
	  `$(CERNLIB) geant321 mathlib graflib grafX11` \
	   $(NETLIB) $(XLIBS) $(GLIBS)

install: hdgeant hdgeant++
	cp $^ $(HALLD_HOME)/bin/$(OStype)

.F.o:
	$(F77) $(FOPTS) -I. -I$(CERN_ROOT)/include -DCERNLIB_MOTIF -c -o $@ $<

.f.o:
	$(F77) $(FOPTS) -I. -I$(CERN_ROOT)/include -c -o $@ $<

.c.o:
	$(CC) $(COPTS) -I. -I../include -I$(CERN_ROOT)/include -c -o $@ $<

$(AUXC): hddm_s.h bintree.h geant3.h hddmOutput.h 

.cpp.o:
	$(CPP) $(COPTS) -I. -I../include -c -o $@ $<

hddm_s.h:
	$(HDDM)/hddm-c $(HDDM)/event.xml

hddm_s.c:
	$(HDDM)/hddm-c $(HDDM)/event.xml

hddm_s.o: 	hddm_s.c
	$(CC) $(COPTS) -I. -I../include -c -o $@ $<

$(GELHAD):
	$(MAKE) -C gelhad

clean:
	rm -f *.o core last.kumac* paw.metafile
