
PACKAGES := CERNLIB
MISC_LIBS = -L/sw/lib -lXm -L/usr/X11R6/lib -lXt -lgelhad -lhitutil
#FFLAGS = -Wno-globals
CFLAGS += -I$(HALLD_HOME)/src/libraries/HDDM
ADDITIONAL_MODULES += HDDM

LD = $(FC)

include $(HALLD_HOME)/src/BMS/Makefile.bin

