
CXXFLAGS += -I$(JANA_HOME)/include
LIB_DIRS += $(JANA_HOME)/lib

ifdef XERCESCROOT
	include $(HALLD_HOME)/src/BMS/Makefile.XERCES
endif

ifdef EVIOROOT
	include $(HALLD_HOME)/src/BMS/Makefile.EVIO
endif


ADDITIONAL_MODULES += JANA
