# This defines flags which can implement (or not) features
# in a way compatible with this OS

OSXFLAGS = -DBASENAME_IN_LIBGEN -DXDR_LONGLONG_MISSING

CFLAGS += $(OSXFLAGS)
CXXFLAGS += $(OSXFLAGS)
LD_FLAGS += -multiply_defined suppress -bind_at_load

LD_SO_FLAGS += -dynamiclib -r -multiply_defined suppress -flat_namespace -undefined suppress
