
CFLAGS		+= -I$(EVIOROOT)/include
CXXFLAGS		+= -DUSE_EVIO -I$(EVIOROOT)/include
MISC_LIBS 	+= -L$(EVIOROOT)/lib -levioxx -levio -lexpat

# The following is a temporary fix to accomodate the
# ET channel in the latest EVIO package.  1/28/2013  DL
include $(HALLD_HOME)/src/BMS/Makefile.ET


