#
#
# $Header$
#

# Things common to both library and executable builds live in Makefile.common
include $(HALLD_HOME)/src/BMS/Makefile.common


LD = $(CXX)

MISC_LIBS_SunOS	+= -lz
MISC_LIBS_Linux	+=
MISC_LIBS			+= -lpthread
MISC_LIBS			+= $(MISC_LIBS_$(OSNAME))

ifdef DEBUG
	LD_FLAGS	+= -g -pg
endif

MAIN_FILES = $(shell grep -l " main" $(CSRC) $(CXXSRC))
MAIN_FILES += $(shell grep -l -i "      PROGRAM " $(FSRC))
EXE_NAMES = $(addsuffix $(DEBUG_SUFFIX),$(basename $(MAIN_FILES)))
MAIN_OBJS =  $(addsuffix .o,$(EXE_NAMES))

# Redefine OBJS to include debug suffixes
DOBJS = $(addsuffix $(DEBUG_SUFFIX).o,$(basename $(OBJS)))
NON_MAIN_OBJS = $(filter-out $(MAIN_OBJS),$(DOBJS))

OBJ_DIR = obj/$(OSNAME)
OUTPUT_OPTION = -o $(OBJ_DIR)/$@
VPATH = $(OBJ_DIR):$(BIN_DIR)
MISC_LIBS += $(addprefix $(OBJ_DIR)/,$(NON_MAIN_OBJS))


LIB_DIRS = $(LIB_DIR)
LD_DIRS = $(addprefix -L,$(LIB_DIRS))
MODULES += $(ADDITIONAL_MODULES)
LD_LIBS = $(addsuffix $(DEBUG_SUFFIX),$(addprefix -l,$(MODULES)))


BINARY = $(BIN_DIR)/$(EXE_NAME)

.PHONY:  mkbindir

all: mkobjdir mkbindir $(EXE_NAMES)

$(EXE_NAMES): $(LD_LIBS) $(DOBJS)
	$(LD) $(LD_FLAGS) $(LD_DIRS) \
		$(LD_LIBS) $(MYSQL_LIBS) $(MISC_LIBS) $(OBJ_DIR)/$@.o \
		-o $(BIN_DIR)/$@

# Rules to make DEBUG objects from source
%_d.o : %.cpp
	$(CXX) -c $(CXXFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.cc
	$(CXX) -c $(CXXFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.cxx
	$(CXX) -c $(CXXFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.c
	$(CC) -c $(CFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.F
	$(FC) -c $(FFLAGS) $< $(OUTPUT_OPTION)


mkbindir:
	@mkdir -p $(BIN_DIR)

mkobjdir:
	@mkdir -p $(OBJ_DIR)

clean:
	rm -rf $(LIBNAME) $(OBJ_DIR) *.o $(EXE_NAMES) *.bak *~ core last.kumac*  #*# 

env:
	@echo FC			     = $(FC)
	@echo CC			     = $(CC)
	@echo CXX		     = $(CXX)
	@echo FFLAGS	     = $(FFLAGS)
	@echo CFLAGS	     = $(CFLAGS)
	@echo CXXFLAGS	     = $(CXXFLAGS)
	@echo FSRC		     = $(FSRC)
	@echo CSRC		     = $(CSRC)
	@echo CXXSRC	     = $(CXXSRC)
	@echo LIBS		     = $(LIBS)
	@echo OSNAME	     = $(OSNAME)
	@echo OBJS		     = $(OBJS)
	@echo LIBNAME	     = $(LIBNAME)
	@echo DEPS		     = $(DEPS)
	@echo EXENAME	     = $(EXENAME)
	@echo LD_LIBS       = $(LD_LIBS)
	@echo MISC_LIBS     = $(MISC_LIBS)
	@echo ROOTLIBS      = $(ROOTLIBS)
	@echo VPATH		     = $(VPATH)
	@echo MODULE_NAME   = $(MODULE_NAME)
	@echo MODULES       = $(MODULES)
	@echo MAIN_FILES    = "$(MAIN_FILES)"
	@echo MAIN_OBJS     = $(MAIN_OBJS)
	@echo NON_MAIN_OBJS = $(NON_MAIN_OBJS)


