#
#
# $Header$
#


# Things common to both library and executable builds live in Makefile.common
include $(HALLD_HOME)/src/BMS/Makefile.common

.PHONY: mkdirs clean env

ifeq ($(LD), ld)
 LD = $(CXX)
endif

MISC_LIBS_SunOS	+= -lz
MISC_LIBS_Linux	+=
MISC_LIBS			+= -lpthread
MISC_LIBS			+= $(MISC_LIBS_$(OSNAME))

ifdef DEBUG
	LD_FLAGS	+= -g -pg
endif

ifneq ($(strip $(CSRC) $(CXXSRC)),)
MAIN_FILES = $(shell grep -l " main" $(CSRC) $(CXXSRC))
endif

ifneq ($(strip $(FSRC)),)
MAIN_FILES += $(shell grep -l -i "      PROGRAM " $(FSRC))
endif

EXE_NAMES = $(addsuffix $(DEBUG_SUFFIX),$(basename $(MAIN_FILES)))
EXE_PATHNAMES = $(foreach s,$(EXE_NAMES),$(BIN_DIR)/$s)
MAIN_OBJS =  $(addsuffix .o,$(EXE_NAMES))

# Redefine OBJS to include debug suffixes
DOBJS = $(addsuffix $(DEBUG_SUFFIX).o,$(basename $(OBJS)))
NON_MAIN_OBJS = $(filter-out $(MAIN_OBJS),$(DOBJS))

OBJ_DIR = obj/$(OSNAME)
OUTPUT_OPTION = -o $(OBJ_DIR)/$@
VPATH = $(OBJ_DIR):$(BIN_DIR)
LINK_OBJS += $(addprefix $(OBJ_DIR)/,$(NON_MAIN_OBJS))


LIB_DIRS = $(LIB_DIR)
LD_DIRS = $(addprefix -L,$(LIB_DIRS))
MODULES += $(ADDITIONAL_MODULES)
LD_LIBS = $(addsuffix $(DEBUG_SUFFIX),$(addprefix -l,$(MODULES)))


BINARY = $(BIN_DIR)/$(EXE_NAME)

.PHONY:  mkdirs

all: mkdirs $(DEPS) $(EXE_NAMES)

$(EXE_NAMES): $(DOBJS)
	$(LD) $(LD_FLAGS) $(LD_DIRS) \
		$(OBJ_DIR)/$@.o $(LINK_OBJS) $(MISC_LIBS) $(LD_LIBS) $(MYSQL_LIBS) \
		-o $(BIN_DIR)/$@

mkdirs:
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(DEP_DIR)

clean:
	rm -rf $(OBJ_DIR) .depends *.o $(EXE_PATHNAMES) *.bak *~ core last.kumac*  #*# 

# Rules to make DEPENDS files from source. Note that these are similar to the
# rules in Makefile.lib, but uses the objects explicitly
%.d : %.cpp
	@$(DCXX) -MM -MT "$(basename $@).o" $(CXXFLAGS) $< > $(DEP_DIR)/$(basename $@).d
%.d : %.cc
	@$(DCXX) -MM -MT "$(basename $@).o" $(CXXFLAGS) $< > $(DEP_DIR)/$(basename $@).d
%.d : %.cxx
	@$(DCXX) -MM -MT "$(basename $@).o" $(CXXFLAGS) $< > $(DEP_DIR)/$(basename $@).d
%.d : %.c
	@$(DCC) -MM -MT "$(basename $@).o" $(CFLAGS) $< > $(DEP_DIR)/$(basename $@).d
%.d : %.F
	@$(DFC) -MM -MT "$(basename $@).o" $(FFLAGS) $< > $(DEP_DIR)/$(basename $@).d

# Rules to make DEBUG objects from source. Note for programs, we give the
# objects funny names while for libraries only the library has a funny name.
%_d.o : %.cpp
	$(CXX) -c $(CXXFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.cc
	$(CXX) -c $(CXXFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.cxx
	$(CXX) -c $(CXXFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.c
	$(CC) -c $(CFLAGS) $< $(OUTPUT_OPTION)
%_d.o : %.F
	$(FC) -c $(FFLAGS) $< $(OUTPUT_OPTION)


env:
	@echo FC			     = $(FC)
	@echo CC			     = $(CC)
	@echo CXX		     = $(CXX)
	@echo LD            = $(LD)
	@echo FFLAGS	     = $(FFLAGS)
	@echo CFLAGS	     = $(CFLAGS)
	@echo CXXFLAGS	     = $(CXXFLAGS)
	@echo FSRC		     = $(FSRC)
	@echo CSRC		     = $(CSRC)
	@echo CXXSRC	     = $(CXXSRC)
	@echo LIBS		     = $(LIBS)
	@echo OSNAME	     = $(OSNAME)
	@echo OBJS		     = $(OBJS)
	@echo LIBNAME	     = $(LIBNAME)
	@echo DEPS		     = $(DEPS)
	@echo EXE_NAMES     = $(EXE_NAMES)
	@echo LD_LIBS       = $(LD_LIBS)
	@echo MISC_LIBS     = $(MISC_LIBS)
	@echo ROOTLIBS      = $(ROOTLIBS)
	@echo VPATH		     = $(VPATH)
	@echo MODULE_NAME   = $(MODULE_NAME)
	@echo MODULES       = $(MODULES)
	@echo MAIN_FILES    = "$(MAIN_FILES)"
	@echo MAIN_OBJS     = $(MAIN_OBJS)
	@echo NON_MAIN_OBJS = $(NON_MAIN_OBJS)


