#
#
# $Header$
#

# Things common to both library and executable builds live in Makefile.common
include $(HALLD_HOME)/src/BMS/Makefile.common



.PHONY: mklibdir


# First rule makes sure directories exist for output files
all: mklibdir $(LIBNAME)($(OBJS))
ifeq ($(OSNAME),Darwin)
	ranlib $(LIBNAME)
endif

$(LIBNAME)($(OBJS)): 

mklibdir:
	@mkdir -p $(LIB_DIR)

clean:
	rm -f $(LIBNAME) *.bak *~ core last.kumac*  #*# 


env:
	@echo FC			= $(FC)
	@echo CC			= $(CC)
	@echo CXX		= $(CXX)
	@echo FFLAGS	= $(FFLAGS)
	@echo CFLAGS	= $(CFLAGS)
	@echo CXXFLAGS	= $(CXXFLAGS)
	@echo FSRC		= $(FSRC)
	@echo CSRC		= $(CSRC)
	@echo CXXSRC	= $(CXXSRC)
	@echo LIBS		= $(LIBS)
	@echo OSNAME	= $(OSNAME)
	@echo OBJS		= $(OBJS)
	@echo LIBNAME	= $(LIBNAME)
	@echo DEPS		= $(DEPS)

