#
#
# $Header$
#

# Things common to both library and executable builds live in Makefile.common
include $(HALLD_HOME)/src/BMS/Makefile.common

.PHONY: mkdirs clean env

VPATH = $(DEP_DIR)

# First rule. Make sure directories and dependancy files exist
all: mkdirs $(DEPS) $(LIBNAME)($(OBJS))
ifeq ($(OSNAME),Darwin)
	ranlib $(LIBNAME)
endif

mkdirs:
	@mkdir -p $(LIB_DIR)
	@mkdir -p $(DEP_DIR)

clean:
	rm -rf $(LIBNAME) .depends *.bak *~ core last.kumac*  #*# 

# Rules to make DEPENDS files from source. Note that these are similar to the
# rules in Makefile.bin, but use the implicit rules for archiving objects.
%$(DEBUG_SUFFIX).d : %.cpp
	@$(CXX) -MM -MT "$(LIBNAME)($(basename $@).o)" $(CXXFLAGS) $< > $(DEP_DIR)/$@
%$(DEBUG_SUFFIX).d : %.cc
	@$(CXX) -MM -MT "$(LIBNAME)($(basename $@).o)" $(CXXFLAGS) $< > $(DEP_DIR)/$@
%$(DEBUG_SUFFIX).d : %.cxx
	@$(CXX) -MM -MT "$(LIBNAME)($(basename $@).o)" $(CXXFLAGS) $< > $(DEP_DIR)/$@
%$(DEBUG_SUFFIX).d : %.c
	@$(CC) -MM -MT "$(LIBNAME)($(basename $@).o)" $(CFLAGS) $< > $(DEP_DIR)/$@
%$(DEBUG_SUFFIX).d : %.F
	@$(FC) -MM -MT "$(LIBNAME)($(basename $@).o)" $(FFLAGS) $< > $(DEP_DIR)/$@


env:
	@echo FC			= $(FC)
	@echo CC			= $(CC)
	@echo CXX		= $(CXX)
	@echo FFLAGS	= $(FFLAGS)
	@echo CFLAGS	= $(CFLAGS)
	@echo CXXFLAGS	= $(CXXFLAGS)
	@echo FSRC		= $(FSRC)
	@echo CSRC		= $(CSRC)
	@echo CXXSRC	= $(CXXSRC)
	@echo LIBS		= $(LIBS)
	@echo OSNAME	= $(OSNAME)
	@echo OBJS		= $(OBJS)
	@echo LIBNAME	= $(LIBNAME)
	@echo DEP_DIR	= $(DEP_DIR)
	@echo DEPS		= $(DEPS)
	@echo TMP		= $(TMP)

