#
#
# $Header$
#

# Things common to both library and executable builds live in Makefile.common
include $(HALLD_HOME)/src/BMS/Makefile.common


LD = $(CXX)

MISC_LIBS_SunOS	+= -lz
MISC_LIBS_Linux	+=
MISC_LIBS			+= -lpthread
MISC_LIBS			+= $(MISC_LIBS_$(OSNAME))

ifdef DEBUG
	LD_FLAGS	+= -g -pg
endif

# Some things (like GEANT) may need to link objects directly rather
# than using a library. Add "USE_OBJECTS := 1" to local Makefile
ifdef USE_OBJECTS
	OBJ_DIR = obj/$(OSNAME)
	OUTPUT_OPTION = -o $(OBJ_DIR)/$@
	VPATH = $(OBJ_DIR)
	MISC_LIBS += $(addprefix $(OBJ_DIR)/,$(OBJS))
else
	MODULES = $(MODULE_NAME)
	VPATH = $(LIB_DIR)
	MISC_LIBS += -l$(MODULE_NAME)$(DEBUG_SUFFIX)
endif


ifndef EXE_NAME
	EXE_NAME = $(MODULE_NAME)$(DEBUG_SUFFIX)
endif


LIB_DIRS = $(LIB_DIR)
LD_DIRS = $(addprefix -L,$(LIB_DIRS))
MODULES += $(ADDITIONAL_MODULES)
LD_LIBS = $(addsuffix $(DEBUG_SUFFIX),$(addprefix -l,$(MODULES)))


BINARY = $(BIN_DIR)/$(EXE_NAME)

.PHONY:  mkbindir

all: mklib mkbin

mklib: mklibdir $(LIBNAME)($(OBJS))
ifeq ($(OSNAME),Darwin)
	ranlib $(LIBNAME)
endif

mkbin: mkbindir $(BINARY)

$(BINARY): $(LD_LIBS)
	$(LD) $(LD_FLAGS) $(LD_DIRS) \
		$(LD_LIBS) $(MYSQL_LIBS) $(MISC_LIBS) \
		-o $@

mkobj: mkobjdir $(OBJS)

mkbindir:
	@mkdir -p $(BIN_DIR)

mklibdir:
	@mkdir -p $(LIB_DIR)

mkobjdir:
	@mkdir -p $(OBJ_DIR)

clean:
	rm -rf $(LIBNAME) $(OBJ_DIR) *.bak *~ core last.kumac*  #*# 

env:
	@echo FC			= $(FC)
	@echo CC			= $(CC)
	@echo CXX		= $(CXX)
	@echo FFLAGS	= $(FFLAGS)
	@echo CFLAGS	= $(CFLAGS)
	@echo CXXFLAGS	= $(CXXFLAGS)
	@echo FSRC		= $(FSRC)
	@echo CSRC		= $(CSRC)
	@echo CXXSRC	= $(CXXSRC)
	@echo LIBS		= $(LIBS)
	@echo OSNAME	= $(OSNAME)
	@echo OBJS		= $(OBJS)
	@echo LIBNAME	= $(LIBNAME)
	@echo DEPS		= $(DEPS)
	@echo EXENAME	= $(EXENAME)
	@echo LD_LIBS  = $(LD_LIBS)
	@echo MISC_LIBS= $(MISC_LIBS)
	@echo ROOTLIBS = $(ROOTLIBS)
	@echo VPATH		= $(VPATH)
	@echo MODULE_NAME = $(MODULE_NAME)
	@echo MODULES   = $(MODULES)


