

FFLAGS += -I$(CERN)/$(CERN_LEVEL)/include
CFLAGS += -I$(CERN)/$(CERN_LEVEL)/include
CXXFLAGS += -I$(CERN)/$(CERN_LEVEL)/include
CERNLIBS = $(shell cernlib geant321 pawlib graflib grafX11 packlib mathlib kernlib)

ifneq "$(OSNAME)" "SunOS"
# MISC_LIBS += -lg2c
endif

MISC_LIBS += $(CERNLIBS) $(EXTRA_LIBS)

ifeq "$(OSNAME)" "Darwin"
  MISC_LIBS += -L/usr/local/lib -lgfortran
endif

