


all:
	make -C genr8 install
	make -C genr8_2_hddm
	make -C hdds
	make -C HDGeant
	make -C mcsmear


clean:
	make -C genr8 clean
	make -C genr8_2_hddm clean
	make -C hdds clean
	make -C HDGeant clean
	make -C mcsmear clean
