#!/bin/bash
source /home/brash/.bash_profile
execname=$1
username=$2
execdir1="/raid0/halld/bin/AlphaLinux"
execdir2="/raid0/halld/bin/OSF1"
make hddsGeant3.f
cd ../../HDGeant
make hdgeant
cp hdgeant $execdir1/$username/$execname
cp hdgeant $execdir2/$username/$execname
cd ../hdds/$username
