#!/bin/sh
./bcalgeomgen6 -a 0.1 -b 0.1 -c 0.1 -d 0.1 -e 0.1 -s 0.5
cp bcalgeomgen.xml BarrelEMcal_HDDS.xml
make hddsGeant3.f
cd ../HDGeant
make hdgeant hdgeant++
cp hdgeant ../../bin/OSF1/hdgeant_0.2mm
cp hdgeant++ ../../bin/OSF1/hdgeant_0.2mm++
cp hdgeant ../../bin/AlphaLinux/hdgeant_0.2mm
cp hdgeant++ ../../bin/AlphaLinux/hdgeant_0.2mm++
cd ../hdds
./bcalgeomgen6 -a 0.25 -b 0.25 -c 0.25 -d 0.25 -e 0.25 -s 0.5
cp bcalgeomgen.xml BarrelEMcal_HDDS.xml
make hddsGeant3.f
cd ../HDGeant
make hdgeant hdgeant++
cp hdgeant ../../bin/OSF1/hdgeant_0.5mm
cp hdgeant++ ../../bin/OSF1/hdgeant_0.5mm++
cp hdgeant ../../bin/AlphaLinux/hdgeant_0.5mm
cp hdgeant++ ../../bin/AlphaLinux/hdgeant_0.5mm++
cd ../hdds
./bcalgeomgen6 -a 0.5 -b 0.5 -c 0.5 -d 0.5 -e 0.5 -s 0.5
cp bcalgeomgen.xml BarrelEMcal_HDDS.xml
make hddsGeant3.f
cd ../HDGeant
make hdgeant hdgeant++
cp hdgeant ../../bin/OSF1/hdgeant_1.0mm
cp hdgeant++ ../../bin/OSF1/hdgeant_1.0mm++
cp hdgeant ../../bin/AlphaLinux/hdgeant_1.0mm
cp hdgeant++ ../../bin/AlphaLinux/hdgeant_1.0mm++
cd ../hdds
./bcalgeomgen6 -a 0.1 -b 0.1 -c 0.25 -d 0.25 -e 0.25 -s 0.5
cp bcalgeomgen.xml BarrelEMcal_HDDS.xml
make hddsGeant3.f
cd ../HDGeant
make hdgeant hdgeant++
cp hdgeant ../../bin/OSF1/hdgeant_0.2_0.5mm
cp hdgeant++ ../../bin/OSF1/hdgeant_0.2_0.5mm++
cp hdgeant ../../bin/AlphaLinux/hdgeant_0.2_0.5mm
cp hdgeant++ ../../bin/AlphaLinux/hdgeant_0.2_0.5mm++
cd ../hdds
./bcalgeomgen6 -a 0.25 -b 0.25 -c 0.1 -d 0.1 -e 0.1 -s 0.5
cp bcalgeomgen.xml BarrelEMcal_HDDS.xml
make hddsGeant3.f
cd ../HDGeant
make hdgeant hdgeant++
cp hdgeant ../../bin/OSF1/hdgeant_0.5_0.2mm
cp hdgeant++ ../../bin/OSF1/hdgeant_0.5_0.2mm++
cp hdgeant ../../bin/AlphaLinux/hdgeant_0.5_0.2mm
cp hdgeant++ ../../bin/AlphaLinux/hdgeant_0.5_0.2mm++
cd ../hdds
