
PACKAGES := CERNLIB:JANA:CURL
MISC_LIBS = -L/sw/lib -lXm -L/usr/X11R6/lib -lXt -lgelhad -lhitutil
#FFLAGS = -Wno-globals
CFLAGS += -I$(HALLD_MY)/src/libraries/HDDM -I$(HALLD_HOME)/src/libraries/HDDM
ADDITIONAL_MODULES += HDDM HDGEOMETRY



include $(HALLD_HOME)/src/BMS/Makefile.bin

