
import sbms

Import('*')

subdirs = ['acceptance_hists', 'b1pi_hists', 'cdc_hists', 'DAQTree', 'DAQTreeBCAL', 'fcal_hists', 'mcthrown_hists', 'trackeff_hists', 'monitoring_hists','dc_alignment','p2pi_hists','p3pi_hists']
sbms.OptionallyBuild(env, ['phys_tree', 'mc_tree', 'pedestals','bcal_calib','bcal_calib_cosmic_cdc'])
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

