


all:
	make -C acceptance_hists
	make -C bcal_hists
	make -C cdc_hists
	make -C fcal_hists
	make -C track_hists
	make -C mcthrown_hists

install:
	make -C acceptance_hists install
	make -C bcal_hists install
	make -C cdc_hists install
	make -C fcal_hists install
	make -C track_hists install
	make -C mcthrown_hists install


clean:
	make -C acceptance_hists clean
	make -C bcal_hists clean
	make -C cdc_hists clean
	make -C fcal_hists clean
	make -C track_hists clean
	make -C mcthrown_hists clean

pristine:
	make -C acceptance_hists pristine
	make -C bcal_hists pristine
	make -C cdc_hists pristine
	make -C fcal_hists pristine
	make -C track_hists pristine
	make -C mcthrown_hists pristine


