


all:
	make -C acceptance_hists
	make -C bcal_hists
	make -C cdc_hists
	make -C fcal_hists
	make -C track_hists
	make -C mcthrown_hists


clean:
	make -C acceptance_hists clean
	make -C bcal_hists clean
	make -C cdc_hists clean
	make -C fcal_hists clean
	make -C track_hists clean
	make -C mcthrown_hists clean


