
import sbms

Import('*')

# Default targets (always built)
subdirs = ['ReactionFilter', 'b1pi_hists']
subdirs.extend(['DAQTree', 'DAQTreeBCAL'])
subdirs.extend(['monitoring_hists'])
subdirs.extend(['p2pi_hists','p3pi_hists','p4pi_hists','p2k_hists'])
subdirs.extend(['p2gamma_hists','ppi0gamma_hists','p2pi0_hists'])
subdirs.extend(['fcal_charged','mcthrown_tree','TPOL_tree'])
subdirs.extend(['pid_dirc','trackeff_hists','imaging'])
subdirs.extend(['B3pi_eff_missgamma','B3pi_eff_misspip','B3pi_eff_misspim','B3pi_eff_missprot'])
SConscript(dirs=subdirs, exports='env osname', duplicate=0)


# Optional targets
optdirs = ['phys_tree', 'pedestals','bcal_calib','bcal_calib_cosmic_cdc']
optdirs.extend(['acceptance_hists', 'mcthrown_hists', 'cdc_hists', 'fcal_hists'])
optdirs.extend(['dc_alignment','p2pi_trees','Z2pi_trees'])
sbms.OptionallyBuild(env, optdirs)

