
import sbms

Import('*')

# Default targets (always built)
subdirs = ['danarest']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

# Optional targets
sbms.OptionallyBuild(env, ['DAQ', 'TTab','rawevent'])
