
import sbms

Import('*')

# Default targets (always built)
subdirs = ['danarest', 'DAQ', 'TTab', 'rawevent', 'evio_writer', '2trackskim', 'pi0fcalskim']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

# Optional targets
sbms.OptionallyBuild(env, ['danahddm', 'dumpcandidates', 'dumpthrowns'])
