
import os
import sbms

# get env object and clone it
Import('*')
env = env.Clone()

# Add directory above this to source so
# TTab will be included
env.AppendUnique(CPPPATH=['%s/..' % env.Dir('.').srcnode().abspath])

sbms.AddEVIO(env)
sbms.AddJANA(env)
sbms.AddET(env)
#sbms.AddCODAChannels(env)
sbms.AddROOT(env)
sbms.library(env)


