      integer writenohits, showersincol, driftclusters, runtime_geom
      real tgtwidth
      integer get_next_evt
      real trigger_time_sigma_ns
      integer event_count
      common /controlparams/ writenohits, showersincol, driftclusters
     +                       ,tgtwidth(2),runtime_geom,get_next_evt
     +                       ,trigger_time_sigma_ns
     +                       ,event_count
