
import sbms

Import('*')

# Default targets (always built)
subdirs = ['analysis', 'root_merge', 'root2email']
subdirs.extend( ['hddm', 'hddm_cull_events', 'hddm_merge_files'])
subdirs.extend( ['mkplugin', 'mkfactory_plugin'] )
subdirs.extend( ['hdevio_scan', 'hdbeam_current', 'hdevio_sample'] )
subdirs.extend( ['mergeTrees'] )

SConscript(dirs=subdirs, exports='env osname', duplicate=0)

# Optional targets (can only be built from inside
# source directory or if specified on command line)
optdirs = ['hdfast_parse', 'hddm2root', 'dumpwires']
optdirs.extend(['evio_merge_events', 'evio_merge_files', 'evio_cull_events', 'evio_check'])
optdirs.extend(['mkMaterialMap','material2root','hddm_select_events'])
optdirs.extend(['bfield2root', 'dumpwires','hd_geom_query'])
sbms.OptionallyBuild(env, optdirs)


