import sbms
Import('*')

subdirs = [
'occupancy_online',
'lowlevel_online',
'BCAL_online',
'BCAL_LEDonline',
'CDC_online',
'DAQ_online',
'FCAL_online',
'FCAL_invmass',
'FDC_online',
'FDC_Efficiency',
'PSC_online',
'RF_online',
'pedestal_online',
'PS_online',
'PSPair_online',
'ST_online_lowlevel',
'ST_online_tracking',
'ST_online_Tresolution',
'ST_online_efficiency',
'ST_online_multi',
'TAGGER_online',
'TAGH_online',
'TAGM_online',
'TAGM_clusters',
'TOF_online',
'TRIG_online',
'TPOL_online',
'CDC_expert',
'CDC_expert_2',
'TOF_TDC_shift',
'BCAL_Eff',
'BCAL_inv_mass',
'CDC_drift',
'CDC_Cosmics',
'EPICS_dump',
'CDC_Efficiency',
'L1_online',
'highlevel_online',
'BCAL_Hadronic_Eff',
'FCAL_Hadronic_Eff',
'SC_Eff','TOF_Eff',
'TS_scaler',
'TrackingPulls'
]

#'L3_online',
#'CODA_online',
#'EVNT_online',


sbms.OptionallyBuild(env, ['TAGH_doubles'])
SConscript(dirs=subdirs, exports='env osname', duplicate=0)
