
Import('*')

subdirs = [
'BCAL_online',
'BCAL_LEDonline',
'CDC_online',
'DAQ_online',
'FCAL_online',
'FDC_online',
'PSC_online',
'RF_online',
'pedestal_online',
'PS_online',
'PSPair_online',
'ST_online_lowlevel',
'ST_online_tracking',
'ST_online_Tresolution',
'ST_online_efficiency',
'TAGGER_online',
'TAGH_online',
'TAGM_online',
'TOF_online',
'TRIG_online',
'TPOL_online',
'CDC_expert',
'CDC_expert_2',
'TOF_TDC_shift',
'BCAL_Eff',
'BCAL_inv_mass',
'CDC_drift',
'CDC_Cosmics',
'EPICS_dump' ,
'CDC_Efficiency']

#'L3_online',
#'CODA_online',
#'EVNT_online',


SConscript(dirs=subdirs, exports='env osname', duplicate=0)

