
import os
import sbms

# get env object and clone it
Import('*')

# Verify AMPTOOLS environment variable is set
if os.getenv('AMPTOOLS', 'nada')!='nada' and os.getenv('CERN', 'nada')!='nada':

	env = env.Clone()
	
	sbms.AddCERNLIB(env)
	sbms.AddAmpTools(env)
	sbms.AddROOT(env)
	sbms.library(env)


