
include $(HALLD_HOME)/src/BMS/Makefile.common

first: install

install:
	mkdir -p $(INSTALL_DIR)/include
	install -p *.h $(INSTALL_DIR)/include

depclean clean pristine:
	@echo depclean clean and pristine targets bypassed in include

