

import sbms

# get env object and clone it
Import('*')
env = env.Clone()

env.AppendUnique(LIBS=['expat','dl','pthread'])

env.AppendUnique(CXXFLAGS=['-std=c++0x'])

sbms.AddEVIO(env)
sbms.AddDANA(env)
sbms.executable(env)


