
CXXFLAGS += -I/home/garmon/coda/Linux-i686/include
.PHONY: all install clean pristine

PACKAGES := cMsg
SOLIB_NAME = janaded.so

ifndef BMSDIR
BMSDIR := ../../../BMS
endif
include $(BMSDIR)/Makefile.config

include $(BMSDIR)/Makefile.shlib
