#include <DObject.h>
#include <DBCALHit.h>
#include <DCDCHit.h>
#include <DFCALGeometry.h>
#include <DFCALHit.h>
#include <DFCALMCResponse.h>
#include <DFCALShower.h>
#include <DFDCHit.h>
#include <DGeometry.h>
#include <DHDDMForwardShower.h>
#include <DHDDMTOFHit.h>
#include <DHDDMTOFTruth.h>
#include <DMCThrown.h>
#include <DMCTrackHit.h>
#include <DParameter.h>
#include <DQuickFit.h>
#include <DTOFGeometry.h>
#include <DTOFHit.h>
#include <DTOFMCResponse.h>
#include <DTOFPoint.h>
#include <DTrackCandidate.h>
#include <DTrackEfficiency.h>
#include <DTrack.h>
#include <DTrackHit.h>

class DObject;
class DBCALHit;
class DCDCHit;
class DFCALGeometry;
class DFCALHit;
class DFCALMCResponse;
class DFCALShower;
class DFDCHit;
class DGeometry;
class DHDDMForwardShower;
class DHDDMTOFHit;
class DHDDMTOFTruth;
class DMCThrown;
class DMCTrackHit;
class DParameter;
class DQuickFit;
class DTOFGeometry;
class DTOFHit;
class DTOFMCResponse;
class DTOFPoint;
class DTrackCandidate;
class DTrackEfficiency;
class DTrack;
class DTrackHit;
