
import sbms

Import('*')

# update this when plugins are added
subdirs = ['BCAL_attenlength_gainratio','BCAL_TDC_Timing','HLDetectorTiming']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

