
import sbms

Import('*')

# update this when plugins are added
subdirs = ['BCAL_attenlength_gainratio','BCAL_gainmatrix','BCAL_TDC_Timing','HLDetectorTiming','TAGH_timewalk','CDC_TimeToDistance','PS_timing']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

