
import sbms

Import('*')

# update this when plugins are added
subdirs = ['BCAL_attenlength_gainratio','BCAL_gainmatrix','BCAL_point_time','BCAL_TDC_Timing','CDC_amp','HLDetectorTiming','TAGH_timewalk','CDC_TimeToDistance','PS_timing','PSC_TW','PS_E_calib','st_tw_corr_auto','ST_Propagation_Time','ST_Tresolution','TAGM_TW','TOF_calib']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

sbms.OptionallyBuild(env, ['FCALgains','FCALpedestals'])
