
import sbms

Import('*')

Import('env osname')

subdirs = ['Analysis', 'Utilities', 'Simulation', 'monitoring', 'Calibration', 'include', 'Alignment']
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

