#! gnumake

#---------------------------------------------------
# The stripped down genr8 Makefile 
#---------------------------------------------------
#

CFLAGS = -D_FILE_OFFSET_BITS=64

INCLUDE := -I. -I$(HALLD_HOME)/src/include -I$(HALLD_HOME)/src/libraries/include
CC = cc

ifndef UNAME
UNAME = $(shell uname)
endif

PROGRAM= genr8

genr8: genr8.o genkin.o
	$(CC) $(CFLAGS) -o $@  $^  -lm

genr8.o: genr8.c
	$(CC) $(CFLAGS) -c -o genr8.o   genr8.c $(INCLUDE)

genkin.o: genkin.c
	$(CC) $(CFLAGS) -c -o genkin.o   genkin.c $(INCLUDE)

clean:
	@rm  *.o 

install: genr8
	mv genr8 $(HALLD_HOME)/bin/$(UNAME)

