#include <iostream>
#include <vector>
#include <iomanip>
#include <fstream>
using namespace std;

#include "CLHEP/Vector/LorentzVector.h"
#include "IUAmpTools/Kinematics.h"
#include "AMPTOOLS_DATAIO/ROOTDataReader.h"
#include "HDDM/hddm_s.h"
#include "particleType.h"

char *INPUT_FILE=NULL;
//char OUTPUT_FILE[] = "output.hddm";
char *OUTPUT_FILE=NULL;
string TREENAME;
vector<int> PTYPE;

void ParseCommandLineArguments(int narg,char *argv[]);
void Usage(void);
double randm(double, double);

float vertex[4]={0.0, 0.0, 65.0, 65.0};

time_t now;

//-------------------------------
// main
//-------------------------------
int main(int narg, char *argv[])
{
  //some defaults
  TREENAME="kin";
  char defOutFName[]="output.hddm";
  OUTPUT_FILE=defOutFName;
  
  ParseCommandLineArguments(narg,argv);
	
  
  // Seed the random generator
  now=time(NULL);
  srand48(now);
  
  ROOTDataReader reader(INPUT_FILE,TREENAME);
	
  // Open output file
  s_iostream_t* thisOutputStream = init_s_HDDM(OUTPUT_FILE);
  if(!thisOutputStream){
    cerr<<"Unable to open output file \""<<OUTPUT_FILE<<"\" for writing."<<endl;
    exit(-3);
  }
  
  // Loop over events
  const Kinematics *kin;

  int runNumber=9000, Nevents=0;
  
  for (unsigned int eventNumber=0;
       eventNumber < reader.numEvents() ; ++eventNumber){
    // get event
    kin=reader.getEvent();
    int nParticles=kin->particleList().size();
    
    // Start a new event in the HDDM record
    s_PhysicsEvents_t* pes;
    s_Reactions_t* rs;
    s_Vertices_t* vs;
    s_Origin_t* origin;
    s_Products_t* ps;
    s_HDDM_t *thisOutputEvent = make_s_HDDM();
    thisOutputEvent->physicsEvents = pes = make_s_PhysicsEvents(1);
    pes->mult = 1;
    pes->in[0].runNo = runNumber;
    pes->in[0].eventNo = eventNumber;
    pes->in[0].reactions = rs = make_s_Reactions(1);
    rs->mult = 1;
    rs->in[0].vertices = vs = make_s_Vertices(1);
    vs->mult = 1;
    vs->in[0].origin = origin = make_s_Origin();
    vs->in[0].products = ps = make_s_Products(nParticles);
    ps->mult = 0;
    
    origin->t = 0.0;
    origin->vx = vertex[0];
    origin->vy = vertex[1];
    
    if(vertex[2]<vertex[3])
      origin->vz = randm(vertex[2],vertex[3]);
    else 
      origin->vz = vertex[2];
    
    
    for(int i=0;i<nParticles;i++, ps->mult++){
      
      ps->in[ps->mult].type = (Particle_t)PTYPE[i];
      ps->in[ps->mult].pdgtype = 0;    /* don't bother with the PDG type here */
      ps->in[ps->mult].id = i+1;       /* unique value for this particle within the event */
      ps->in[ps->mult].parentid = 0;   /* All internally generated particles have no parent */
      ps->in[ps->mult].mech = 0;       /* maybe this should be set to something? */
      ps->in[ps->mult].momentum = make_s_Momentum();
      ps->in[ps->mult].momentum->px = kin->particle(i).px();
      ps->in[ps->mult].momentum->py = kin->particle(i).py();
      ps->in[ps->mult].momentum->pz = kin->particle(i).pz();
      ps->in[ps->mult].momentum->E  = kin->particle(i).e();
      
    }
    
    if(nParticles>0){
      flush_s_HDDM(thisOutputEvent, thisOutputStream);
      if(eventNumber%1000 == 0)cout<<"Wrote event "<<eventNumber<<endl;
      Nevents++;
    }
  }
  
  // Close output file
  close_s_HDDM(thisOutputStream);
  
  cout<<"Processed "<<Nevents<<" events"<<endl;
  
  return 0;
}

//-------------------------------
// ParseCommandLineArguments
//-------------------------------
void ParseCommandLineArguments(int narg,char *argv[])
{
  if(narg<2){
    Usage();
    exit(0);
  }
  char *ptypestr;
  
  for(int i=1;i<narg;i++){
    if(argv[i][0]=='-'){
      char *ptr = &argv[i][1];
      switch(*ptr){
      case 'V':
	sscanf(&ptr[1], "%f %f %f %f", &vertex[0], &vertex[1], &vertex[2], &vertex[3]);
	if(vertex[2] > vertex[3]){
	  cerr<<"Invalid parameter: z_min > z_max"<< endl;
	  exit(-1);
	}
	break;
      case 'P':
	ptypestr=strtok(&ptr[1]," ");
	while(ptypestr!=NULL){
	  PTYPE.push_back(atoi(ptypestr));
	  ptypestr=strtok(NULL," ");
	}
	break;
      case 'T':
	TREENAME=&ptr[1];
	break;
      case 'o':
	OUTPUT_FILE=&ptr[1];
	break;
      default:
	cerr<<"Unknown option \""<<argv[i]<<"\""<<endl;
	Usage();
	exit(-1);
      }
    }else{
      INPUT_FILE = argv[i];
    }
  }
}

//-------------------------------
// Usage
//-------------------------------
void Usage(void)
{
  cout<<endl;
  cout<<"Usage:"<<endl;
  cout<<"       genr8_2_hddm [options] file.ascii"<<endl;
  cout<<endl;
  cout<<"Convert an ascii file of events generated by genr8 into HDDM"<<endl;
  cout<<"for use as input to hdgeant."<<endl;
  cout<<endl;
  cout<<" options:"<<endl;
  cout<<endl;
  cout<<"  -P\"ptype1 ptype2 ...\"     set the vertex for the interaction." <<endl;
  cout<<"  -o[output_file_name]      name of output file (default: output.hddm)"<<endl;
  cout<<"  -T[tree_name]             set name of tree in ROOT file default: kin)"<<endl;
  cout<<"  -V\"x  y  z_min  z_max\"    set the vertex for the interaction."<<endl;
  cout<<"(default: x="<<vertex[0]<<" y="<<vertex[1]<<" z_min="<<vertex[2]<<" z_max="<<vertex[3]<<")"<<endl;
  cout<<"  -h           print this usage statement."<<endl;
  cout<<endl;
}


/**************************/
/*  Random generator      */
/*------------------------*/
double randm(double low, double high)
{
  return ((high - low) * drand48() + low);
}
