
import sbms

Import('*')

# Default targets (always built)
subdirs = ['danarest', 'evio_writer']
subdirs.extend(['2trackskim', 'pi0bcalskim', 'pi0fcalskim', 'run_summary', 'track_skimmer', 'trackeff_missing','ps_skim', 'trigger_skims', 'bigevents_skim', 'coherent_peak_skim','exclusivepi0skim'])
subdirs.extend(['EventTagPi0','es_test','omega_skim','cal_high_energy_skim'])
SConscript(dirs=subdirs, exports='env osname', duplicate=0)

# Optional targets
optdirs = ['danahddm', 'dumpcandidates', 'dumpthrowns', 'l3bdt']
optdirs.extend(['merge_rawevents', 'syncskim', 'DAQ', 'TTab', 'rawevent'])
sbms.OptionallyBuild(env, optdirs)
