

import sbms

# get env object and clone it
Import('*')
env = env.Clone()

sbms.AddCERNLIB(env)
env.AppendUnique(FORTRANFLAGS=['-DCERNLIB_TYPE', '-D_GELH_', '-DCERNLIB_TYPE'])
env.AppendUnique(FORTRANPATH=['..'])
sbms.library(env)


