
      real *4 mgam/0.0/
      real *4 mnu/0.0/
      real *4 mw/80.8/
      real *4 mz/92.9/
      real *4 mmu/0.10565932/
      real *4 mtau/1.7770/
      real *4 me/0.0005110034/
      real *4 mpich/0.1395673/
      real *4 mpi0/0.1349630/
      real *4 meta/0.5488/
      real *4 mkch/0.493667/
      real *4 mphi/1.020/
      real *4 mk0/0.49767/
      real *4 mdch/1.8694/
      real *4 md0/1.8647/
      real *4 mdstr/2.0101/
      real *4 mf/1.971/
      real *4 mbch/5.276/
      real *4 mb0/5.276/
      real *4 mbs/5.6/
      real *4 mbc/6.0/
      real *4 mp/0.9382796/
      real *4 mn/0.9395731/
      real *4 mlda/1.1156/
      real *4 mspls/1.18936/
      real *4 ms0/1.19246/
      real *4 msmns/1.19734/
      real *4 mpsi/3.0960/


