import sbms
from subprocess import call

Import('*')
env = env.Clone()
#env.Append(IGNORE_SOURCES = {'DrcHit_Dict.cc','DrcEvent_Dict.cc'})
sbms.AddDANA(env)
env.Replace(OPTIONAL_PLUGIN_LIBS = [''])
sbms.plugin(env)





