
import os
import sbms

# get env object and clone it
Import('*')
env = env.Clone()

env.AppendUnique(LIBS=['DAQ']);

# MYSQL
env.ParseConfig("mysql_config --cflags")
env.ParseConfig("mysql_config --libs")

sbms.AddEVIO(env)
sbms.AddJANA(env)
sbms.AddROOT(env)
sbms.AddCCDB(env)
sbms.plugin(env)


