
import os
import sbms

# get env object and clone it
Import('*')
env = env.Clone()

# Add directory above this to source so
# TTab will be included
env.AppendUnique(CPPPATH=['%s/..' % env.Dir('.').srcnode().abspath])

sbms.AddDANA(env)
sbms.AddROOT(env)
sbms.AddEVIO(env)
sbms.AddET(env)
sbms.AddCODAChannels(env)
sbms.plugin(env)


