
import sbms

Import('*')

subdirs = ['fit', 'twopi_plotter', 'twopi_plotter_amp', 'twopi_plotter_primakoff', 'split_mass', 'threepi_plotter_schilling', 'omega_radiative_plotter']

SConscript(dirs=subdirs, exports='env osname', duplicate=0)

