


all:
	make -C hddm
	make -C hd_ana
	make -C hd_dump
	make -C hd_root
	make -C mctrk_ana
	make -C plugins
	make -C hdview

clean:
	make -C hddm clean
	make -C hd_ana clean
	make -C hd_dump clean
	make -C hd_root clean
	make -C mctrk_ana clean
	make -C plugins clean
	make -C hdview clean

pristine:
	make -C hd_ana pristine
	make -C hd_dump pristine
	make -C hd_root pristine
	make -C mctrk_ana pristine
	make -C plugins pristine
	make -C hdview pristine

