


all:
	make -C hddm
	make -C hd_ana
	make -C hd_dump
	make -C hdview
	make -C mctrk_ana

clean:
	make -C hddm clean
	make -C hd_ana clean
	make -C hd_dump clean
	make -C hdview clean
	make -C mctrk_ana clean
