
PACKAGES := XERCES
MISC_LIBS = -L/sw/lib -lXm -L/usr/X11R6/lib -lXt -lf2c -lg2c -lcompat -lgelhad

include $(HALLD_DIR)/src/BMS/Makefile.bin

c: hddm-c hddm-cpp
	hddm-c event.xml
	hddm-cpp event.xml

install: c
	mv hddm_s.h hddm_s.hpp $(HALLD_HOME)/src/libraries/include
	mv hddm_s.c hddm_containers_s.cc $(HALLD_HOME)/src/libraries/HDDM
	
klean:
	rm -f hddm_s.h hddm_s.hpp hddm_s.c hddm_containers_s.cc
